%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: ./imgs/Viking/
feature_path: ./data/features.yml
filename_path: ./data/feature_name.txt
matrix_path: ./data/similarityMatrix.yml
match_path: ./data/match_info.yml

num_features: 150
num_features_init: 50
num_features_tracking: 50
